create TABLE funcionarios (
	matricula varchar(10) primary key,
	nome varchar(100) not null,
	email varchar(100),
	coordenacao varchar(50),
	profissao varchar(50)
);

INSERT INTO funcionarios (matricula, nome, email, coordenacao, profissao) VALUES 
('MT-8842', 'Ricardo Mendes Oliveira', 'ricardo.mendes@empresa.com', 'Equipamentos', 'Engenheiro I'),
('MT-1059', 'Luciana Prates Silva', 'luciana.prates@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-9321', 'Fabricio Torres', 'fabricio.torres@empresa.com', 'Sistemas', 'Especialista'),
('MT-4470', 'Daniela Guimarães', 'daniela.guimaraes@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-2155', 'Anderson Carvalho', 'anderson.carvalho@empresa.com', 'Preditiva', 'Engenheiro Especialista'),
('MT-7732', 'Beatriz Farias', 'beatriz.farias@empresa.com', 'Sistemas', 'Técnico de Desenvolvimento I'),
('MT-1290', 'Carlos Eduardo Lima', 'carlos.lima@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento II'),
('MT-5501', 'Gustavo Henrique', 'gustavo.henrique@empresa.com', 'Sistemas', 'Engenheiro II'),
('MT-3387', 'Helena Schimidt', 'helena.schimidt@empresa.com', 'Equipamentos', 'Especialista'),
('MT-6612', 'Igor Vinicius Rocha', 'igor.rocha@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento II'),
('MT-2245', 'Juliana Meireles', 'juliana.meireles@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-8890', 'Kleber Machado Dias', 'kleber.dias@empresa.com', 'Equipamentos', 'Engenheiro Especialista'),
('MT-4123', 'Leandro Castilho', 'leandro.castilho@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-9904', 'Monica Silveira', 'monica.silveira@empresa.com', 'Sistemas', 'Técnico de Desenvolvimento II'),
('MT-1156', 'Nelson Barbosa', 'nelson.barbosa@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-7741', 'Rodrigo Siqueira', 'rodrigo.siqueira@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-3329', 'Sandra Helena', 'sandra.helena@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento I'),
('MT-5582', 'Thiago Américo', 'thiago.americo@empresa.com', 'Preditiva', 'Engenheiro II'),
('MT-9012', 'Wagner Ribeiro', 'wagner.ribeiro@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento II'),
('MT-2278', 'Yuri Fonseca', 'yuri.fonseca@empresa.com', 'Preditiva', 'Especialista'),
('MT-4411', 'Aline Pereira', 'aline.pereira@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-6654', 'Marcos Vinícius', 'marcos.vinicius@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento I'),
('MT-1132', 'Carla Pimentel', 'carla.pimentel@empresa.com', 'Preditiva', 'Engenheiro II'),
('MT-8821', 'Diego Lugano', 'diego.lugano@empresa.com', 'Sistemas', 'Especialista'),
('MT-5599', 'Eduardo Paes', 'eduardo.paes@empresa.com', 'Equipamentos', 'Engenheiro Especialista'),
('MT-3345', 'Flavia Alessandra', 'flavia.alessandra@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento II'),
('MT-7788', 'Gabriel Barbosa', 'gabriel.barbosa@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-2210', 'Hugo Mattos', 'hugo.mattos@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-9933', 'Isadora Ribeiro', 'isadora.ribeiro@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-4456', 'Jorge Aragão', 'jorge.aragao@empresa.com', 'Sistemas', 'Especialista'),
('MT-1177', 'Letícia Spiller', 'leticia.spiller@empresa.com', 'Equipamentos', 'Engenheiro Especialista'),
('MT-6609', 'Luan Santana', 'luan.santana@empresa.com', 'Preditiva', 'Engenheiro I'),
('MT-8843', 'Malu Mader', 'malu.mader@empresa.com', 'Sistemas', 'Técnico de Desenvolvimento II'),
('MT-3311', 'Nívea Stelmann', 'nivea.stelmann@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-5542', 'Otávio Müller', 'otavio.muller@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-2267', 'Paula Fernandes', 'paula.fernandes@empresa.com', 'Sistemas', 'Especialista'),
('MT-9911', 'Quitéria Chagas', 'quiteria.chagas@empresa.com', 'Equipamentos', 'Engenheiro I'),
('MT-4422', 'Renato Gaúcho', 'renato.gaucho@empresa.com', 'Preditiva', 'Engenheiro Especialista'),
('MT-1109', 'Solange Almeida', 'solange.almeida@empresa.com', 'Sistemas', 'Técnico de Desenvolvimento II'),
('MT-7755', 'Tais Araújo', 'tais.araujo@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-3399', 'Uodson Silva', 'uodson.silva@empresa.com', 'Preditiva', 'Especialista'),
('MT-5521', 'Valéria Valenssa', 'valeria.valenssa@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-2289', 'Wilson Witzel', 'wilson.witzel@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento I'),
('MT-8866', 'Xande Valois', 'xande.valois@empresa.com', 'Preditiva', 'Engenheiro II'),
('MT-4433', 'Yasmin Santos', 'yasmin.santos@empresa.com', 'Sistemas', 'Engenheiro Especialista'),
('MT-1122', 'Zeca Camargo', 'zeca.camargo@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento II'),
('MT-6677', 'Arthur Aguiar', 'arthur.aguiar@empresa.com', 'Preditiva', 'Especialista'),
('MT-9944', 'Bruna Linzmeyer', 'bruna.linzmeyer@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-3355', 'Caio Blat', 'caio.blat@empresa.com', 'Equipamentos', 'Técnico de Desenvolvimento I'),
('MT-5511', 'Dalton Vigh', 'dalton.vigh@empresa.com', 'Preditiva', 'Engenheiro II'),
('MT-2233', 'Emanuelle Araújo', 'emanuelle.araujo@empresa.com', 'Sistemas', 'Especialista'),
('MT-8811', 'Fiuk Moraes', 'fiuk.moraes@empresa.com', 'Equipamentos', 'Engenheiro Especialista'),
('MT-4400', 'Giovanna Ewbank', 'giovanna.ewbank@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento II'),
('MT-1144', 'Humberto Carrão', 'humberto.carrao@empresa.com', 'Sistemas', 'Engenheiro I'),
('MT-6633', 'Ísis Valverde', 'isis.valverde@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-9922', 'Joaquim Lopes', 'joaquim.lopes@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-3366', 'Kleber Bambam', 'kleber.bambam@empresa.com', 'Equipamentos', 'Engenheiro II'),
('MT-5533', 'Larissa Manoela', 'larissa.manoela@empresa.com', 'Preditiva', 'Técnico de Desenvolvimento I'),
('MT-2200', 'Murilo Benício', 'murilo.benicio@empresa.com', 'Sistemas', 'Especialista'),
('MT-8855', 'Nathalia Dill', 'nathalia.dill@empresa.com', 'Equipamentos', 'Engenheiro I');

select * from funcionarios;

